/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StaffMember = IDL.Record({
  'staffId' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inReview' : IDL.Null,
});
export const IssueType = IDL.Variant({
  'technicalBug' : IDL.Null,
  'generalFeedback' : IDL.Null,
  'paymentIssue' : IDL.Null,
  'sessionConnectionIssue' : IDL.Null,
  'accountLoginProblem' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'attachmentUrl' : IDL.Opt(ExternalBlob),
  'status' : TicketStatus,
  'issueType' : IssueType,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'ticketId' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'assignedStaff' : IDL.Opt(IDL.Text),
  'sessionId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'adminResponse' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addStaffMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignStaffToTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getAllTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getTicketStatus' : IDL.Func(
      [IDL.Text],
      [TicketStatus, IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getTicketsByStatus' : IDL.Func(
      [TicketStatus],
      [IDL.Vec(SupportTicket)],
      ['query'],
    ),
  'respondToTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitTicket' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IssueType,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'updateTicketStatus' : IDL.Func([IDL.Text, TicketStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StaffMember = IDL.Record({
    'staffId' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inReview' : IDL.Null,
  });
  const IssueType = IDL.Variant({
    'technicalBug' : IDL.Null,
    'generalFeedback' : IDL.Null,
    'paymentIssue' : IDL.Null,
    'sessionConnectionIssue' : IDL.Null,
    'accountLoginProblem' : IDL.Null,
  });
  const SupportTicket = IDL.Record({
    'attachmentUrl' : IDL.Opt(ExternalBlob),
    'status' : TicketStatus,
    'issueType' : IssueType,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'ticketId' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'assignedStaff' : IDL.Opt(IDL.Text),
    'sessionId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'adminResponse' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addStaffMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignStaffToTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getAllTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getTicketStatus' : IDL.Func(
        [IDL.Text],
        [TicketStatus, IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getTicketsByStatus' : IDL.Func(
        [TicketStatus],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'respondToTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitTicket' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IssueType,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'updateTicketStatus' : IDL.Func([IDL.Text, TicketStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };