/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type IssueType = { 'technicalBug' : null } |
  { 'generalFeedback' : null } |
  { 'paymentIssue' : null } |
  { 'sessionConnectionIssue' : null } |
  { 'accountLoginProblem' : null };
export interface StaffMember {
  'staffId' : string,
  'name' : string,
  'role' : string,
}
export interface SupportTicket {
  'attachmentUrl' : [] | [ExternalBlob],
  'status' : TicketStatus,
  'issueType' : IssueType,
  'name' : string,
  'createdAt' : bigint,
  'ticketId' : string,
  'email' : string,
  'message' : string,
  'assignedStaff' : [] | [string],
  'sessionId' : [] | [string],
  'phone' : string,
  'adminResponse' : [] | [string],
}
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inReview' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addStaffMember' : ActorMethod<[string, string, string], undefined>,
  'assignStaffToTicket' : ActorMethod<[string, string], undefined>,
  'getAllStaffMembers' : ActorMethod<[], Array<StaffMember>>,
  'getAllTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getTicketStatus' : ActorMethod<[string], [TicketStatus, [] | [string]]>,
  'getTicketsByStatus' : ActorMethod<[TicketStatus], Array<SupportTicket>>,
  'respondToTicket' : ActorMethod<[string, string], undefined>,
  'submitTicket' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      IssueType,
      string,
      [] | [ExternalBlob],
    ],
    string
  >,
  'updateTicketStatus' : ActorMethod<[string, TicketStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];